# Generated by Django 4.0.3 on 2022-03-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
