# Generated by Django 4.0.3 on 2022-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='channel_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
