# Generated by Django 4.0.4 on 2022-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactteam',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
